---
title: "SEIR模型"
author: "xuexuan"
date: "2020/4/1"
output:
  html_document: default
  pdf_document: default
---

<font size = 5> 


## **3　SEIR模型**
　　考虑某种传染性疾病在人群中的传播, 在任何时刻, 每一个体都处于如下 4 种状态之一:  
　　(1)易感态(susceptible, S), 即个体处于病源的传染范围内, 是高危人群;  
　　(2)潜伏态(exposed, E), 即个体已被病源感染, 但还没有发病;  
　　(3)传染态(infectious, I), 即个体已经发病, 具传染性, 症状可能因个体而异;  
　　(4)移除态(recovered/removed, R; 或称为康净态),即个体或康复, 或因被隔离或死亡等原因而
处于一种无传染性的净置状态.如果是康复, 康复者未必能获得对该病毒的完全免疫力, 所以, 这些个
体可能再次处于病源的辐射范围内, 即 R → S.  
令F(t)、G(t)、R(t)分别是在时间段[0,t]里已处于潜伏态、传染态和康净态的个体累积总数,则  
<div align=center>  
$$E(t):=F(t)-G(t),     I(t):=G(t)-R(t)\tag{3.1}$$
</div>  
是在时间点 t 时处于潜伏态和传染态的个体数, 其相应的初始条件是  
<div align=center>  
$$F(0) \geq 0,  G(0)=0, R(0)=0\tag{3.2}$$  
</div>  
　　根据我们先前的工作，可建立关于不同状态转移S → E →I → R 关系:   
<div align=center>   
$$F'(t)=r(t) \cdot (G(t)-R(t))   　　　 (S → E),\tag{3.3}$$ $$G(t)=\int^{t}_{0}{F(t-s)W'(s)ds}    　　　(E → I),\tag{3.4}$$
$$R(t)=\int^{t}_{0}{G'(s)A(s,t-s)ds}　　(I → R),\tag{3.5}$$  
</div>  
这里用到了上一节所给的积分模型方程, 其中(3.4)和(3.5)刻画 E → I 和 I → R 这两个转移过
程, 而方程 (3.3) 描述转移过程 S → E, 另外,  
　　(1)r(t)是非负的有界函数, 它表示在 t 时刻, 单位时间里每个传染者所具有的平均传染率(mean
infection rate per unit time per active infective), 称为即时平均传染率.一般地, r(t) 的值依赖于控制效率.  
　　(2)W(t) 是一个潜伏患者在被感染 t 单位时间后成为传染者的概率.故W是非减函数, W(0) = 0,且当t → $\infty$ 时，W(t) → 1.  
　　(3)A(t,s)是一个恰好在时刻 t 成为传染者的个体,在经过 s 单位时间后进入恢复态的概率.故对于任意固定的 t，A(t, s) 是 s 的非减函数,且当s → $\infty$ 时,A(t, s) → 1.一般地, A(t, s) 的值依赖于控制效率.  
　　下面给出传染病动力学模型最基本量, 即有效再生数的计算式:  
<div align=center>  
$$R_{eff}(t):= \int^{\infty}_{0}{r(t+s)(1-A(t,s))ds}　　(t \geq 0),\tag{3.6}$$  
</div>  
它代表在疾病传播过程中, 在时间 t 的一个染病患者在其病程内平均传染的患者数, 它是一个随时间
变化的量, 也是病毒传播是否能够维持的指标.  
$$G(t)=F(0)W(t)+\int^{t}_{0}{F'(s)W(t-s)ds}$$
$$G(t)=\int^{t}_{0}{W(t-s)d(F(s)}$$
$$G(t)=-\int^{t}_{0}{F(s)W'(t-s)(-1)d(s)}$$ 
令u=t-s,则  
$$G(t)=\int^{0}_{t}{F(t-u)W'(u)d(t-u)}$$
$$G(t)=\int^{t}_{0}{F(t-u)W'(u)d(u)}$$
$$G(t)=\int^{t}_{0}{F(t-s)W'(s)ds} 　　(E → I)$$


