---
title: "protect"
author: "cui219"
date: "2020/3/30"
output:
  html_document:
    toc: yes
---

## 1 卷积积分模型

### 1.1卷积积分的定义

&emsp;&emsp;设有两个函数$f_1(t)$和$f_2(t)$,积分

<center>$f(t)=\int_{-\infty}^{\infty}{f_1(\tau)f_2(t-\tau)}{d\tau}$</center>

称为$f_1(t)$和$f_2(t)$的卷积积分，简称积分，记作

<center>$f(t)=f_1(t)*f_2(t)$或$f(t)={f_1(t)}\bigotimes{f_2(t)}$</center>

其中$t$是指观察响应的时刻，是积分的参变量；$\tau$是指信号作用的时刻，是积分变量.

利用卷积分可以求解系统的零状态响应.

### 1.2完全转移模式: 卷积积分模型

&emsp;&emsp;考虑群体中的个体状态转移,即一个个体要历经两种紧接相续的状态,先状态*X*后状态*Y*,且从状态*X* 到状态*Y*的转移是完全的.也就是说,群体中的个体只要进入状态*X*,那么它必然在以后的某个时间点进入到状态*Y*.

### 1.3 一般概率转移模式

&emsp;&emsp;为描述转移过程*X*→*Y*,令$X(t)$(相应地,$Y(t)$)是群体中的个体处于状态*X*(相应地,状态*Y*)从开始点$t_0= 0$直至某个时间点$t>0$的累积总数.显然,

<center>*X*和*Y*均为递增函数.</center>

&emsp;&emsp;**转移概率**&emsp;假定一个恰在时间点 s 进入状态*X*的个体,在后来的时间点${t}\geq{s}$正好进入状态*Y*的概率是$P(t − s)$, 或等价地, 此个体在后来的时间点*t*仍然处于状态*X*的概率是$1 − P(t − s)$.进一步假设这个转移过程*X*→*Y*是齐性, 而且服从于一个累积分布函数 (cumulative distribution function,CDF) *P*:$\mathbb{R}_+{\to}[0, 1]$, 其满足

<center>$P(0)=0$,$\displaystyle \lim_{t\to \infty}P(t)=1$,$\mu:=\int_{0}^{\infty}{(1-P(t))}{dt}<\infty$</center>

其中$\mu=\int_{0}^{\infty}{(1-P(t))}{dt}$为$X\to Y$的平均转移时间,并将这个转移过程记作$X \displaystyle \to^{P}{Y}$.一般地,$\mu$叫作*P*的期望值.显然, 函数 *X*与*Y*可以通过转移概率建立联系, 下面导出二者的关系.

&emsp;&emsp;**函数*X*与*Y*的关系**&emsp;对给定t > 0, 将区间[0, t]分成n+1个等距的子区间

<center>$\lbrace {\Delta_i:}={[t_i,t_{i+1}]:{0 \leq i\leq n}}\rbrace$,$t_i:=i\Delta t$,$\Delta t=\frac{t}{n-1}$</center>

考虑$\Delta_i=[t_i,t_{i+1}]$.显然有下面的等式:

<center>$X(t_{i+1})-X(t_i)=在\Delta_i时段里进入X 态的个体总数$.</center>

因此，

<center>$(X(t_{i+1})-X(t_i))\times P(t-t_i) \approx上述处于 X 态的成员将在未来的时间点 t 进入 Y 态的个体数$.</center>

另外，那些在起始点0就处于*X*态的成员(数量为$X(0)$), 在经历了*t*单位时间后将进入*Y*态的部分, 数量值是 $X(0)P(t)$. 故有

<center>$Y(t)\approx X(0)P(t)+\displaystyle \sum_i(X(t_{i+1})-X(t_i))\times P(t-t_i)$</center>

&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;$\approx X(0)P(t)+\displaystyle \sum_iX^{'}(t_i)\Delta t\times P(t-t_i)$

&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;$=X(0)P(t)+\int_0^tX^{'}(s)P(t-s){ds}$,$当\Delta t\to 0时$.

因此，

<center>$Y(t)=X(0)P(t)+\int_0^tP(t-s)X^{'}(s){ds}$.</center>

通过分部积分并注意到$P(0)=0$，上式可等价地写成

<center>$Y(t)=\int_0^tP^{'}(t-s)X(s){ds}$.</center>

### 1.4一般时间相关的概率转移

&emsp;&emsp;一般地, 若转移概率*P*是时间相关的, 则相应的卷积模型具有如下表达:

<center>$Y(t)=X(0)P(0,t)+\int_0^tX^{'}(s)P(s,t-s){ds}$   $(t\geq 0)$</center>
